-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_13_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 9; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_13_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "110000001", 1 => "101011110", 2 => "101001110", 3 => "110011101", 
    4 => "110001101", 5 => "101001000", 6 => "110100100", 7 => "110001000", 
    8 => "101000010", 9 => "110000111", 10 => "110101011", 11 => "110100101", 
    12 => "101010101", 13 => "101111000", 14 => "110000010", 15 => "110110111", 
    16 => "100111100", 17 => "101011100", 18 => "101110010", 19 => "101101011", 
    20 => "110001001", 21 => "110101010", 22 => "101100110", 23 => "101110101", 
    24 => "110000111", 25 => "110001101", 26 => "110001000", 27 => "101100001", 
    28 => "101111001", 29 => "100111001", 30 => "101100001", 31 => "101011101", 
    32 => "101100110", 33 => "101100001", 34 => "101100000", 35 => "101110010", 
    36 => "101110010", 37 => "101001001", 38 => "101011001", 39 => "110101010", 
    40 => "110011011", 41 => "110110111", 42 => "101101010", 43 => "100100100", 
    44 => "101111000", 45 => "101101101", 46 => "101101101", 47 => "101101100", 
    48 => "110001100", 49 => "101010111", 50 => "101100100", 51 => "101110111", 
    52 => "101111000", 53 => "101000010", 54 => "101011011", 55 => "110011000", 
    56 => "101101110", 57 => "110010001", 58 => "101110011", 59 => "101010001", 
    60 => "101101101", 61 => "110010011", 62 => "110111001", 63 => "101000101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

