set_property SRC_FILE_INFO {cfile:/home/emre/projectZed/projectZed.srcs/constrs_1/new/asd.xdc rfile:../../../projectZed.srcs/constrs_1/new/asd.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[7]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/s_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/custom_fifo_0/m_axis_tdata[7]}]
