#!/bin/bash 
cd /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_2_738qp6bw
vitis_hls /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_2_738qp6bw/hls_syn_StreamingDataflowPartition_1_MVAU_hls_2.tcl
cd /home/emre/Documents/finn
