# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/finn_dev_emre/vivado_zynq_proj_l6ydi7rt/finn_zynq_link.srcs/sources_1/bd/top/ip/top_axi_interconnect_0_imp_xbar_0/top_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'top_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_emre/vivado_zynq_proj_l6ydi7rt/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_interconnect_0_imp_xbar_0/top_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /tmp/finn_dev_emre/vivado_zynq_proj_l6ydi7rt/finn_zynq_link.srcs/sources_1/bd/top/ip/top_axi_interconnect_0_imp_xbar_0/top_axi_interconnect_0_imp_xbar_0.xci
# IP: The module: 'top_axi_interconnect_0_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_emre/vivado_zynq_proj_l6ydi7rt/finn_zynq_link.gen/sources_1/bd/top/ip/top_axi_interconnect_0_imp_xbar_0/top_axi_interconnect_0_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_interconnect_0_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
