#!/bin/bash 
cd /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_2_IODMA_hls_0_8mzee8u5
vitis_hls /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_2_IODMA_hls_0_8mzee8u5/hls_syn_StreamingDataflowPartition_2_IODMA_hls_0.tcl
cd /home/emre/Documents/finn
