-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0101000", 1 => "0001101", 2 => "0001000", 3 => "0101001", 
    4 => "0011111", 5 => "1110101", 6 => "0110011", 7 => "0011100", 
    8 => "0011100", 9 => "0100100", 10 => "0101010", 11 => "0101101", 
    12 => "0001001", 13 => "0111001", 14 => "0101001", 15 => "0100011", 
    16 => "0000100", 17 => "1111101", 18 => "0011011", 19 => "0000010", 
    20 => "0100110", 21 => "0100101", 22 => "0100101", 23 => "0011110", 
    24 => "0110011", 25 => "0111100", 26 => "0100011", 27 => "0101000", 
    28 => "0100011", 29 => "0000000", 30 => "0000011", 31 => "0011101", 
    32 => "0011100", 33 => "0011101", 34 => "0011011", 35 => "0011110", 
    36 => "0001000", 37 => "1111110", 38 => "0001110", 39 => "0011110", 
    40 => "0010100", 41 => "0111010", 42 => "0100100", 43 => "1111111", 
    44 => "0100101", 45 => "0010110", 46 => "0110010", 47 => "1101000", 
    48 => "0011100", 49 => "0010001", 50 => "1111110", 51 => "0011100", 
    52 => "0110001", 53 => "1101001", 54 => "1111010", 55 => "0100100", 
    56 => "0100110", 57 => "0110100", 58 => "0011111", 59 => "0011001", 
    60 => "0011110", 61 => "0011101", 62 => "0101100", 63 => "1101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

