-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_5_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_5_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10011011", 1 => "01111101", 2 => "01110101", 3 => "10100101", 
    4 => "10011001", 5 => "01100110", 6 => "10101110", 7 => "10010101", 
    8 => "01111110", 9 => "10011010", 10 => "10101010", 11 => "10101011", 
    12 => "01111000", 13 => "10100011", 14 => "10011100", 15 => "10101010", 
    16 => "01101100", 17 => "01110010", 18 => "10001101", 19 => "01111010", 
    20 => "10011100", 21 => "10100111", 22 => "10010000", 23 => "10010001", 
    24 => "10100100", 25 => "10101100", 26 => "10011010", 27 => "10010000", 
    28 => "10010101", 29 => "01101000", 30 => "01111000", 31 => "10001000", 
    32 => "10001010", 33 => "10001001", 34 => "10000111", 35 => "10001111", 
    36 => "10000000", 37 => "01101100", 38 => "01111101", 39 => "10100010", 
    40 => "10010111", 41 => "10111001", 42 => "10010000", 43 => "01100001", 
    44 => "10010110", 45 => "10001000", 46 => "10011011", 47 => "01101010", 
    48 => "10010111", 49 => "01111110", 50 => "01110101", 51 => "10010000", 
    52 => "10011110", 53 => "01011100", 54 => "01110000", 55 => "10100000", 
    56 => "10010011", 57 => "10101000", 58 => "10010000", 59 => "10000001", 
    60 => "10001110", 61 => "10011001", 62 => "10110000", 63 => "01011111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

