-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of StreamingDataflowPartition_1_MVAU_hls_1_Matrix_Vector_Activate_Stream_Batch_p_ZL7threshs_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1000101", 1 => "0101001", 2 => "0100100", 3 => "1001000", 
    4 => "0111110", 5 => "0010001", 6 => "1010001", 7 => "0111010", 
    8 => "0110101", 9 => "1000010", 10 => "1001010", 11 => "1001101", 
    12 => "0100101", 13 => "1010100", 14 => "1000110", 15 => "1000101", 
    16 => "0011110", 17 => "0011010", 18 => "0111000", 19 => "0100000", 
    20 => "1000011", 21 => "1000110", 22 => "1000000", 23 => "0111011", 
    24 => "1001111", 25 => "1011000", 26 => "1000001", 27 => "1000010", 
    28 => "0111111", 29 => "0011010", 30 => "0100000", 31 => "0110111", 
    32 => "0111000", 33 => "0111000", 34 => "0110110", 35 => "0111010", 
    36 => "0100110", 37 => "0011001", 38 => "0101010", 39 => "0111111", 
    40 => "0110101", 41 => "1011010", 42 => "0111111", 43 => "0010111", 
    44 => "1000001", 45 => "0110010", 46 => "1001101", 47 => "0001001", 
    48 => "0111011", 49 => "0101100", 50 => "0011100", 51 => "0111001", 
    52 => "1001100", 53 => "0000110", 54 => "0011000", 55 => "1000011", 
    56 => "1000001", 57 => "1010001", 58 => "0111011", 59 => "0110011", 
    60 => "0111010", 61 => "0111100", 62 => "1001101", 63 => "0001001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

