-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_r : IN STD_LOGIC_VECTOR (63 downto 0);
    dma2dwc_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    dma2dwc_full_n : IN STD_LOGIC;
    dma2dwc_write : OUT STD_LOGIC;
    dma2dwc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    dma2dwc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    numReps : IN STD_LOGIC_VECTOR (31 downto 0);
    numReps_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numReps_c_full_n : IN STD_LOGIC;
    numReps_c_write : OUT STD_LOGIC;
    numReps_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    numReps_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (19 downto 0) := "00000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (19 downto 0) := "00000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (19 downto 0) := "00000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (19 downto 0) := "00000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (19 downto 0) := "00000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (19 downto 0) := "00001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (19 downto 0) := "00010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (19 downto 0) := "00100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (19 downto 0) := "01000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (19 downto 0) := "10000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv64_62 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000001100010";
    constant ap_const_lv64_620 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000011000100000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln168_reg_264 : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_c_blk_n : STD_LOGIC;
    signal numReps_read_reg_243 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal in_read_reg_248 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_122_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_253 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln168_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln1_reg_268 : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_done : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_idle : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_ready : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_write : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_done : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_idle : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_ready : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_write : STD_LOGIC;
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal sext_ln140_fu_205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal rep_fu_72 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal rep_3_fu_215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rep_2_fu_225_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln163_fu_139_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln170_fu_148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln170_1_fu_154_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln170_fu_160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln170_2_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln170_fu_172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_178_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln140_fu_186_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln140_fu_190_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln166_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_block_state12_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        dma2dwc_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        dma2dwc_full_n : IN STD_LOGIC;
        dma2dwc_write : OUT STD_LOGIC;
        dma2dwc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dma2dwc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        sext_ln140 : IN STD_LOGIC_VECTOR (60 downto 0) );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        dma2dwc_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        dma2dwc_full_n : IN STD_LOGIC;
        dma2dwc_write : OUT STD_LOGIC;
        dma2dwc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dma2dwc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        sext_ln140 : IN STD_LOGIC_VECTOR (60 downto 0) );
    end component;



begin
    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104 : component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start,
        ap_done => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_done,
        ap_idle => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_idle,
        ap_ready => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_ready,
        m_axi_gmem_0_AWVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST => m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID => m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM => m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP => m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        dma2dwc_din => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_din,
        dma2dwc_full_n => dma2dwc_full_n,
        dma2dwc_write => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_write,
        dma2dwc_num_data_valid => ap_const_lv3_0,
        dma2dwc_fifo_cap => ap_const_lv3_0,
        sext_ln140 => trunc_ln1_reg_268);

    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113 : component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start,
        ap_done => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_done,
        ap_idle => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_idle,
        ap_ready => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_ready,
        m_axi_gmem_0_AWVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST => m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID => m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM => m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP => m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        dma2dwc_din => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din,
        dma2dwc_full_n => dma2dwc_full_n,
        dma2dwc_write => grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_write,
        dma2dwc_num_data_valid => ap_const_lv3_0,
        dma2dwc_fifo_cap => ap_const_lv3_0,
        sext_ln140 => trunc_ln1_reg_268);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln166_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_ready = ap_const_logic_1)) then 
                    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    rep_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rep_fu_72 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_1))) then 
                rep_fu_72 <= rep_2_fu_225_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_0))) then 
                rep_fu_72 <= rep_3_fu_215_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                empty_reg_253 <= empty_fu_122_p1;
                in_read_reg_248 <= in_r;
                numReps_read_reg_243 <= numReps;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln168_reg_264 <= icmp_ln168_fu_143_p2;
                trunc_ln1_reg_268 <= add_ln140_fu_190_p2(63 downto 3);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln168_reg_264, ap_block_state1, ap_CS_fsm_state2, ap_block_state3_io, ap_CS_fsm_state12, icmp_ln166_fu_134_p2, ap_block_state12_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln166_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (ap_const_boolean_0 = ap_block_state12_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln140_fu_190_p2 <= std_logic_vector(unsigned(zext_ln140_fu_186_p1) + unsigned(in_read_reg_248));
    add_ln170_fu_172_p2 <= std_logic_vector(unsigned(sub_ln170_fu_160_p2) + unsigned(shl_ln170_2_fu_166_p2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(ap_block_state12_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state12_on_subcall_done)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_io)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_io)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, numReps_c_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or (numReps_c_full_n = ap_const_logic_0));
    end process;


    ap_block_state12_on_subcall_done_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_done, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_done)
    begin
                ap_block_state12_on_subcall_done <= (((grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_done = ap_const_logic_0) and (icmp_ln168_reg_264 = ap_const_lv1_1)) or ((grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_done = ap_const_logic_0) and (icmp_ln168_reg_264 = ap_const_lv1_0)));
    end process;


    ap_block_state3_io_assign_proc : process(m_axi_gmem_0_ARREADY, icmp_ln168_reg_264)
    begin
                ap_block_state3_io <= (((m_axi_gmem_0_ARREADY = ap_const_logic_0) and (icmp_ln168_reg_264 = ap_const_lv1_0)) or ((m_axi_gmem_0_ARREADY = ap_const_logic_0) and (icmp_ln168_reg_264 = ap_const_lv1_1)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln166_fu_134_p2)
    begin
        if (((icmp_ln166_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    dma2dwc_din_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_din, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
            if ((icmp_ln168_reg_264 = ap_const_lv1_1)) then 
                dma2dwc_din <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din;
            elsif ((icmp_ln168_reg_264 = ap_const_lv1_0)) then 
                dma2dwc_din <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_din;
            else 
                dma2dwc_din <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din;
            end if;
        else 
            dma2dwc_din <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_din;
        end if; 
    end process;


    dma2dwc_write_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_write, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_write, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
            if ((icmp_ln168_reg_264 = ap_const_lv1_1)) then 
                dma2dwc_write <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_dma2dwc_write;
            elsif ((icmp_ln168_reg_264 = ap_const_lv1_0)) then 
                dma2dwc_write <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_dma2dwc_write;
            else 
                dma2dwc_write <= ap_const_logic_0;
            end if;
        else 
            dma2dwc_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_122_p1 <= numReps(4 - 1 downto 0);

    gmem_blk_n_AR_assign_proc : process(m_axi_gmem_0_ARREADY, ap_CS_fsm_state3, icmp_ln168_reg_264)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln168_reg_264 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            gmem_blk_n_AR <= m_axi_gmem_0_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_ap_start_reg;
    grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_ap_start_reg;
    icmp_ln166_fu_134_p2 <= "1" when (rep_fu_72 = numReps_read_reg_243) else "0";
    icmp_ln168_fu_143_p2 <= "1" when (empty_reg_253 = trunc_ln163_fu_139_p1) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln166_fu_134_p2)
    begin
        if (((icmp_ln166_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_0_ARADDR_assign_proc : process(ap_CS_fsm_state3, icmp_ln168_reg_264, ap_block_state3_io, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARADDR, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARADDR, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20, sext_ln140_fu_205_p1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARADDR <= sext_ln140_fu_205_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARADDR <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARADDR;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARADDR <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARADDR;
        else 
            m_axi_gmem_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem_0_ARBURST_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARBURST, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARBURST, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARBURST <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARBURST;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARBURST <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARBURST;
        else 
            m_axi_gmem_0_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem_0_ARCACHE_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARCACHE, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARCACHE, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARCACHE <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARCACHE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARCACHE <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARCACHE;
        else 
            m_axi_gmem_0_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_0_ARID_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARID, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARID, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARID <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARID <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARID;
        else 
            m_axi_gmem_0_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem_0_ARLEN_assign_proc : process(ap_CS_fsm_state3, icmp_ln168_reg_264, ap_block_state3_io, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLEN, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLEN, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_1))) then 
            m_axi_gmem_0_ARLEN <= ap_const_lv64_620(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_0))) then 
            m_axi_gmem_0_ARLEN <= ap_const_lv64_62(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARLEN <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLEN;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARLEN <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLEN;
        else 
            m_axi_gmem_0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem_0_ARLOCK_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLOCK, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLOCK, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARLOCK <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARLOCK;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARLOCK <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARLOCK;
        else 
            m_axi_gmem_0_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem_0_ARPROT_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARPROT, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARPROT, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARPROT <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARPROT;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARPROT <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARPROT;
        else 
            m_axi_gmem_0_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem_0_ARQOS_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARQOS, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARQOS, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARQOS <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARQOS;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARQOS <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARQOS;
        else 
            m_axi_gmem_0_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_0_ARREGION_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARREGION, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARREGION, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARREGION <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARREGION;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARREGION <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARREGION;
        else 
            m_axi_gmem_0_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem_0_ARSIZE_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARSIZE, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARSIZE, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARSIZE <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARSIZE;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARSIZE <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARSIZE;
        else 
            m_axi_gmem_0_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem_0_ARUSER_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARUSER, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARUSER, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARUSER <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARUSER;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARUSER <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARUSER;
        else 
            m_axi_gmem_0_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem_0_ARVALID_assign_proc : process(ap_CS_fsm_state3, icmp_ln168_reg_264, ap_block_state3_io, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARVALID, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARVALID, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_ARVALID <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_ARVALID;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_ARVALID <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_ARVALID;
        else 
            m_axi_gmem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_0_RREADY_assign_proc : process(icmp_ln168_reg_264, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_RREADY, grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_RREADY, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state20)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state20) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_1)))) then 
            m_axi_gmem_0_RREADY <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_1_fu_113_m_axi_gmem_0_RREADY;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state12) and (icmp_ln168_reg_264 = ap_const_lv1_0)))) then 
            m_axi_gmem_0_RREADY <= grp_Mem2Stream_Batch_64u_784u_Pipeline_VITIS_LOOP_140_11_fu_104_m_axi_gmem_0_RREADY;
        else 
            m_axi_gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_0_WDATA <= ap_const_lv64_0;
    m_axi_gmem_0_WID <= ap_const_lv1_0;
    m_axi_gmem_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_0_WSTRB <= ap_const_lv8_0;
    m_axi_gmem_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_0_WVALID <= ap_const_logic_0;

    numReps_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, numReps_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_c_blk_n <= numReps_c_full_n;
        else 
            numReps_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numReps_c_din <= numReps;

    numReps_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            numReps_c_write <= ap_const_logic_1;
        else 
            numReps_c_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rep_2_fu_225_p2 <= std_logic_vector(unsigned(rep_fu_72) + unsigned(ap_const_lv32_10));
    rep_3_fu_215_p2 <= std_logic_vector(unsigned(rep_fu_72) + unsigned(ap_const_lv32_1));
        sext_ln140_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_268),64));

    shl_ln170_1_fu_154_p2 <= std_logic_vector(shift_left(unsigned(rep_fu_72),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln170_2_fu_166_p2 <= std_logic_vector(shift_left(unsigned(rep_fu_72),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln170_fu_148_p2 <= std_logic_vector(shift_left(unsigned(rep_fu_72),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln_fu_178_p3 <= (add_ln170_fu_172_p2 & ap_const_lv3_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln170_fu_160_p2 <= std_logic_vector(unsigned(shl_ln170_fu_148_p2) - unsigned(shl_ln170_1_fu_154_p2));
    trunc_ln163_fu_139_p1 <= rep_fu_72(4 - 1 downto 0);
    zext_ln140_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_178_p3),64));
end behav;
