-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity StreamingDataflowPartition_0_IODMA_hls_0 is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    out_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_V_TVALID : OUT STD_LOGIC;
    out_V_TREADY : IN STD_LOGIC );
end;


architecture behav of StreamingDataflowPartition_0_IODMA_hls_0 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "StreamingDataflowPartition_0_IODMA_hls_0_StreamingDataflowPartition_0_IODMA_hls_0,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1656,HLS_SYN_LUT=2558,HLS_VERSION=2024_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_rst_n_inv : STD_LOGIC;
    signal in0_V : STD_LOGIC_VECTOR (63 downto 0);
    signal numReps : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gmem_0_AWREADY : STD_LOGIC;
    signal gmem_0_WREADY : STD_LOGIC;
    signal gmem_0_ARREADY : STD_LOGIC;
    signal gmem_0_RVALID : STD_LOGIC;
    signal gmem_0_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_0_RLAST : STD_LOGIC;
    signal gmem_0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_0_BVALID : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_ap_start : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_ap_done : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_ap_continue : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_ap_idle : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_ap_ready : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_start_out : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_start_write : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_dma2dwc_din : STD_LOGIC_VECTOR (63 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_dma2dwc_write : STD_LOGIC;
    signal Mem2Stream_Batch_64u_784u_U0_numReps_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Mem2Stream_Batch_64u_784u_U0_numReps_c_write : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID : STD_LOGIC;
    signal StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read : STD_LOGIC;
    signal dma2dwc_full_n : STD_LOGIC;
    signal dma2dwc_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal dma2dwc_empty_n : STD_LOGIC;
    signal dma2dwc_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal dma2dwc_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal numReps_c_full_n : STD_LOGIC;
    signal numReps_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal numReps_c_empty_n : STD_LOGIC;
    signal numReps_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal numReps_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n : STD_LOGIC;
    signal start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n : STD_LOGIC;

    component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r : IN STD_LOGIC_VECTOR (63 downto 0);
        dma2dwc_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        dma2dwc_full_n : IN STD_LOGIC;
        dma2dwc_write : OUT STD_LOGIC;
        dma2dwc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dma2dwc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        numReps : IN STD_LOGIC_VECTOR (31 downto 0);
        numReps_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        numReps_c_full_n : IN STD_LOGIC;
        numReps_c_write : OUT STD_LOGIC;
        numReps_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        numReps_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_StreamingDataWidthConverter_Batch_64u_8u_98u_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dma2dwc_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        dma2dwc_empty_n : IN STD_LOGIC;
        dma2dwc_read : OUT STD_LOGIC;
        dma2dwc_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dma2dwc_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        out_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_V_TVALID : OUT STD_LOGIC;
        out_V_TREADY : IN STD_LOGIC;
        numReps_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        numReps_empty_n : IN STD_LOGIC;
        numReps_read : OUT STD_LOGIC;
        numReps_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        numReps_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_fifo_w64_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in0_V : OUT STD_LOGIC_VECTOR (63 downto 0);
        numReps : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component StreamingDataflowPartition_0_IODMA_hls_0_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component StreamingDataflowPartition_0_IODMA_hls_0_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in0_V => in0_V,
        numReps => numReps,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component StreamingDataflowPartition_0_IODMA_hls_0_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 64,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID,
        I_CH0_ARREADY => gmem_0_ARREADY,
        I_CH0_ARADDR => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR,
        I_CH0_ARLEN => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN,
        I_CH0_RVALID => gmem_0_RVALID,
        I_CH0_RREADY => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY,
        I_CH0_RDATA => gmem_0_RDATA,
        I_CH0_RFIFONUM => gmem_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_0_WREADY,
        I_CH0_WDATA => ap_const_lv64_0,
        I_CH0_WSTRB => ap_const_lv8_0,
        I_CH0_BVALID => gmem_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    Mem2Stream_Batch_64u_784u_U0 : component StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mem2Stream_Batch_64u_784u_U0_ap_start,
        start_full_n => start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n,
        ap_done => Mem2Stream_Batch_64u_784u_U0_ap_done,
        ap_continue => Mem2Stream_Batch_64u_784u_U0_ap_continue,
        ap_idle => Mem2Stream_Batch_64u_784u_U0_ap_idle,
        ap_ready => Mem2Stream_Batch_64u_784u_U0_ap_ready,
        start_out => Mem2Stream_Batch_64u_784u_U0_start_out,
        start_write => Mem2Stream_Batch_64u_784u_U0_start_write,
        m_axi_gmem_0_AWVALID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => gmem_0_RVALID,
        m_axi_gmem_0_RREADY => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => gmem_0_RDATA,
        m_axi_gmem_0_RLAST => gmem_0_RLAST,
        m_axi_gmem_0_RID => gmem_0_RID,
        m_axi_gmem_0_RFIFONUM => gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => gmem_0_RUSER,
        m_axi_gmem_0_RRESP => gmem_0_RRESP,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        in_r => in0_V,
        dma2dwc_din => Mem2Stream_Batch_64u_784u_U0_dma2dwc_din,
        dma2dwc_full_n => dma2dwc_full_n,
        dma2dwc_write => Mem2Stream_Batch_64u_784u_U0_dma2dwc_write,
        dma2dwc_num_data_valid => dma2dwc_num_data_valid,
        dma2dwc_fifo_cap => dma2dwc_fifo_cap,
        numReps => numReps,
        numReps_c_din => Mem2Stream_Batch_64u_784u_U0_numReps_c_din,
        numReps_c_full_n => numReps_c_full_n,
        numReps_c_write => Mem2Stream_Batch_64u_784u_U0_numReps_c_write,
        numReps_c_num_data_valid => numReps_c_num_data_valid,
        numReps_c_fifo_cap => numReps_c_fifo_cap);

    StreamingDataWidthConverter_Batch_64u_8u_98u_U0 : component StreamingDataflowPartition_0_IODMA_hls_0_StreamingDataWidthConverter_Batch_64u_8u_98u_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start,
        ap_done => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done,
        ap_continue => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue,
        ap_idle => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle,
        ap_ready => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready,
        dma2dwc_dout => dma2dwc_dout,
        dma2dwc_empty_n => dma2dwc_empty_n,
        dma2dwc_read => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read,
        dma2dwc_num_data_valid => dma2dwc_num_data_valid,
        dma2dwc_fifo_cap => dma2dwc_fifo_cap,
        out_V_TDATA => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA,
        out_V_TVALID => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID,
        out_V_TREADY => out_V_TREADY,
        numReps_dout => numReps_c_dout,
        numReps_empty_n => numReps_c_empty_n,
        numReps_read => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read,
        numReps_num_data_valid => numReps_c_num_data_valid,
        numReps_fifo_cap => numReps_c_fifo_cap);

    dma2dwc_U : component StreamingDataflowPartition_0_IODMA_hls_0_fifo_w64_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Mem2Stream_Batch_64u_784u_U0_dma2dwc_din,
        if_full_n => dma2dwc_full_n,
        if_write => Mem2Stream_Batch_64u_784u_U0_dma2dwc_write,
        if_dout => dma2dwc_dout,
        if_empty_n => dma2dwc_empty_n,
        if_read => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read,
        if_num_data_valid => dma2dwc_num_data_valid,
        if_fifo_cap => dma2dwc_fifo_cap);

    numReps_c_U : component StreamingDataflowPartition_0_IODMA_hls_0_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Mem2Stream_Batch_64u_784u_U0_numReps_c_din,
        if_full_n => numReps_c_full_n,
        if_write => Mem2Stream_Batch_64u_784u_U0_numReps_c_write,
        if_dout => numReps_c_dout,
        if_empty_n => numReps_c_empty_n,
        if_read => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read,
        if_num_data_valid => numReps_c_num_data_valid,
        if_fifo_cap => numReps_c_fifo_cap);

    start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_U : component StreamingDataflowPartition_0_IODMA_hls_0_start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din,
        if_full_n => start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n,
        if_write => Mem2Stream_Batch_64u_784u_U0_start_write,
        if_dout => start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dout,
        if_empty_n => start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n,
        if_read => StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready);




    Mem2Stream_Batch_64u_784u_U0_ap_continue <= ap_const_logic_1;
    Mem2Stream_Batch_64u_784u_U0_ap_start <= ap_start;
    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue <= ap_const_logic_1;
    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start <= start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n;
    ap_done <= StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done;
    ap_idle <= (StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle and Mem2Stream_Batch_64u_784u_U0_ap_idle);
    ap_ready <= Mem2Stream_Batch_64u_784u_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    gmem_0_RID <= ap_const_lv1_0;
    gmem_0_RLAST <= ap_const_logic_0;
    gmem_0_RRESP <= ap_const_lv2_0;
    gmem_0_RUSER <= ap_const_lv1_0;
    out_V_TDATA <= StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA;
    out_V_TVALID <= StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID;
    start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
