#!/bin/bash 
cd /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_1_2hlhfuts
vitis_hls /tmp/finn_dev_emre/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_1_2hlhfuts/hls_syn_StreamingDataflowPartition_1_MVAU_hls_1.tcl
cd /home/emre/Documents/finn
