// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="StreamingDataflowPartition_0_IODMA_hls_0_StreamingDataflowPartition_0_IODMA_hls_0,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1656,HLS_SYN_LUT=2558,HLS_VERSION=2024_2}" *)

module StreamingDataflowPartition_0_IODMA_hls_0 (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;

 reg    ap_rst_n_inv;
wire   [63:0] in0_V;
wire   [31:0] numReps;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem_0_AWREADY;
wire    gmem_0_WREADY;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
wire   [63:0] gmem_0_RDATA;
wire    gmem_0_RLAST;
wire   [0:0] gmem_0_RID;
wire   [8:0] gmem_0_RFIFONUM;
wire   [0:0] gmem_0_RUSER;
wire   [1:0] gmem_0_RRESP;
wire    gmem_0_BVALID;
wire    Mem2Stream_Batch_64u_784u_U0_ap_start;
wire    Mem2Stream_Batch_64u_784u_U0_ap_done;
wire    Mem2Stream_Batch_64u_784u_U0_ap_continue;
wire    Mem2Stream_Batch_64u_784u_U0_ap_idle;
wire    Mem2Stream_Batch_64u_784u_U0_ap_ready;
wire    Mem2Stream_Batch_64u_784u_U0_start_out;
wire    Mem2Stream_Batch_64u_784u_U0_start_write;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWVALID;
wire   [63:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWADDR;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWID;
wire   [31:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLEN;
wire   [2:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWSIZE;
wire   [1:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWBURST;
wire   [1:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLOCK;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWCACHE;
wire   [2:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWPROT;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWQOS;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWREGION;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWUSER;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WVALID;
wire   [63:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WDATA;
wire   [7:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WSTRB;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WLAST;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WID;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WUSER;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID;
wire   [63:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARID;
wire   [31:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN;
wire   [2:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARSIZE;
wire   [1:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARBURST;
wire   [1:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLOCK;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARCACHE;
wire   [2:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARPROT;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARQOS;
wire   [3:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARREGION;
wire   [0:0] Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARUSER;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY;
wire    Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_BREADY;
wire   [63:0] Mem2Stream_Batch_64u_784u_U0_dma2dwc_din;
wire    Mem2Stream_Batch_64u_784u_U0_dma2dwc_write;
wire   [31:0] Mem2Stream_Batch_64u_784u_U0_numReps_c_din;
wire    Mem2Stream_Batch_64u_784u_U0_numReps_c_write;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read;
wire   [7:0] StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID;
wire    StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read;
wire    dma2dwc_full_n;
wire   [63:0] dma2dwc_dout;
wire    dma2dwc_empty_n;
wire   [2:0] dma2dwc_num_data_valid;
wire   [2:0] dma2dwc_fifo_cap;
wire    numReps_c_full_n;
wire   [31:0] numReps_c_dout;
wire    numReps_c_empty_n;
wire   [2:0] numReps_c_num_data_valid;
wire   [2:0] numReps_c_fifo_cap;
wire   [0:0] start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din;
wire    start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n;
wire   [0:0] start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dout;
wire    start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n;

StreamingDataflowPartition_0_IODMA_hls_0_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in0_V(in0_V),
    .numReps(numReps),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

StreamingDataflowPartition_0_IODMA_hls_0_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR),
    .I_CH0_ARLEN(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

StreamingDataflowPartition_0_IODMA_hls_0_Mem2Stream_Batch_64u_784u_s Mem2Stream_Batch_64u_784u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mem2Stream_Batch_64u_784u_U0_ap_start),
    .start_full_n(start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n),
    .ap_done(Mem2Stream_Batch_64u_784u_U0_ap_done),
    .ap_continue(Mem2Stream_Batch_64u_784u_U0_ap_continue),
    .ap_idle(Mem2Stream_Batch_64u_784u_U0_ap_idle),
    .ap_ready(Mem2Stream_Batch_64u_784u_U0_ap_ready),
    .start_out(Mem2Stream_Batch_64u_784u_U0_start_out),
    .start_write(Mem2Stream_Batch_64u_784u_U0_start_write),
    .m_axi_gmem_0_AWVALID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(gmem_0_RLAST),
    .m_axi_gmem_0_RID(gmem_0_RID),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(gmem_0_RUSER),
    .m_axi_gmem_0_RRESP(gmem_0_RRESP),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(Mem2Stream_Batch_64u_784u_U0_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .in_r(in0_V),
    .dma2dwc_din(Mem2Stream_Batch_64u_784u_U0_dma2dwc_din),
    .dma2dwc_full_n(dma2dwc_full_n),
    .dma2dwc_write(Mem2Stream_Batch_64u_784u_U0_dma2dwc_write),
    .dma2dwc_num_data_valid(dma2dwc_num_data_valid),
    .dma2dwc_fifo_cap(dma2dwc_fifo_cap),
    .numReps(numReps),
    .numReps_c_din(Mem2Stream_Batch_64u_784u_U0_numReps_c_din),
    .numReps_c_full_n(numReps_c_full_n),
    .numReps_c_write(Mem2Stream_Batch_64u_784u_U0_numReps_c_write),
    .numReps_c_num_data_valid(numReps_c_num_data_valid),
    .numReps_c_fifo_cap(numReps_c_fifo_cap)
);

StreamingDataflowPartition_0_IODMA_hls_0_StreamingDataWidthConverter_Batch_64u_8u_98u_s StreamingDataWidthConverter_Batch_64u_8u_98u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start),
    .ap_done(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done),
    .ap_continue(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue),
    .ap_idle(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle),
    .ap_ready(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready),
    .dma2dwc_dout(dma2dwc_dout),
    .dma2dwc_empty_n(dma2dwc_empty_n),
    .dma2dwc_read(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read),
    .dma2dwc_num_data_valid(dma2dwc_num_data_valid),
    .dma2dwc_fifo_cap(dma2dwc_fifo_cap),
    .out_V_TDATA(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA),
    .out_V_TVALID(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID),
    .out_V_TREADY(out_V_TREADY),
    .numReps_dout(numReps_c_dout),
    .numReps_empty_n(numReps_c_empty_n),
    .numReps_read(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read),
    .numReps_num_data_valid(numReps_c_num_data_valid),
    .numReps_fifo_cap(numReps_c_fifo_cap)
);

StreamingDataflowPartition_0_IODMA_hls_0_fifo_w64_d2_S dma2dwc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mem2Stream_Batch_64u_784u_U0_dma2dwc_din),
    .if_full_n(dma2dwc_full_n),
    .if_write(Mem2Stream_Batch_64u_784u_U0_dma2dwc_write),
    .if_dout(dma2dwc_dout),
    .if_empty_n(dma2dwc_empty_n),
    .if_read(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dma2dwc_read),
    .if_num_data_valid(dma2dwc_num_data_valid),
    .if_fifo_cap(dma2dwc_fifo_cap)
);

StreamingDataflowPartition_0_IODMA_hls_0_fifo_w32_d2_S numReps_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Mem2Stream_Batch_64u_784u_U0_numReps_c_din),
    .if_full_n(numReps_c_full_n),
    .if_write(Mem2Stream_Batch_64u_784u_U0_numReps_c_write),
    .if_dout(numReps_c_dout),
    .if_empty_n(numReps_c_empty_n),
    .if_read(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_numReps_read),
    .if_num_data_valid(numReps_c_num_data_valid),
    .if_fifo_cap(numReps_c_fifo_cap)
);

StreamingDataflowPartition_0_IODMA_hls_0_start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0 start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din),
    .if_full_n(start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_full_n),
    .if_write(Mem2Stream_Batch_64u_784u_U0_start_write),
    .if_dout(start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_dout),
    .if_empty_n(start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n),
    .if_read(StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_ready)
);

assign Mem2Stream_Batch_64u_784u_U0_ap_continue = 1'b1;

assign Mem2Stream_Batch_64u_784u_U0_ap_start = ap_start;

assign StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_continue = 1'b1;

assign StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_start = start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_empty_n;

assign ap_done = StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_done;

assign ap_idle = (StreamingDataWidthConverter_Batch_64u_8u_98u_U0_ap_idle & Mem2Stream_Batch_64u_784u_U0_ap_idle);

assign ap_ready = Mem2Stream_Batch_64u_784u_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign gmem_0_RID = 1'd0;

assign gmem_0_RLAST = 1'b0;

assign gmem_0_RRESP = 2'd0;

assign gmem_0_RUSER = 1'd0;

assign out_V_TDATA = StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TDATA;

assign out_V_TVALID = StreamingDataWidthConverter_Batch_64u_8u_98u_U0_out_V_TVALID;

assign start_for_StreamingDataWidthConverter_Batch_64u_8u_98u_U0_din = 1'b1;

endmodule //StreamingDataflowPartition_0_IODMA_hls_0
